# Generated by Django 4.2.3 on 2023-07-22 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='change_date',
            field=models.DateField(default=datetime.date(2023, 7, 22), verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='make_date',
            field=models.DateField(default=datetime.date(2023, 7, 22), verbose_name='Дата создания'),
        ),
    ]
