# Generated by Django 4.2.3 on 2023-07-24 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_change_date_alter_product_make_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name', 'description'), 'verbose_name': 'Категориsя', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'category', 'description'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='change_date',
            field=models.DateField(default=datetime.date(2023, 7, 24), verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='make_date',
            field=models.DateField(default=datetime.date(2023, 7, 24), verbose_name='Дата создания'),
        ),
    ]
