# Generated by Django 4.2.3 on 2023-07-25 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='change_date',
            field=models.DateField(default=datetime.date(2023, 7, 25), verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='make_date',
            field=models.DateField(default=datetime.date(2023, 7, 25), verbose_name='Дата создания'),
        ),
    ]
