# Generated by Django 4.2.3 on 2023-07-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_change_date_alter_product_make_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
