# Generated by Django 4.2.3 on 2023-08-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_change_date_alter_product_make_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
    ]
